import { ScanResult } from '../core/types.js';
import { CATEGORIES } from '../core/rule-ids.js';

export function generateMarkdownReport(result: ScanResult): string {
  const { projectInfo, diagnostics, passedRules, scoreResult, timestamp } = result;

  let md = `# 🏥 Audit Doctor Report — Web Application Production Readiness\n\n`;
  md += `**Project:** \`${projectInfo.projectName}\` | **Framework:** \`${projectInfo.framework}\` | **Date:** ${timestamp}\n\n`;

  md += `## 📊 Health Score Overview\n\n`;
  md += `- **Overall Production Readiness Score:** **${scoreResult.overallScore}/100** (Grade: **${scoreResult.grade}** — *${scoreResult.label}*)\n`;
  md += `- **Total Checklist Items Evaluated:** 39\n`;
  md += `- **Passed Items:** ✅ ${passedRules.length}\n`;
  md += `- **Failed Audits:** ❌ ${scoreResult.errorCount} Errors, ⚠️ ${scoreResult.warningCount} Warnings\n\n`;

  md += `### Category Breakdown\n\n`;
  md += `| Category | Status | Passed / Total | Score |\n`;
  md += `| :--- | :---: | :---: | :---: |\n`;

  for (const catScore of scoreResult.categoryScores) {
    const statusIcon = catScore.percentage >= 80 ? '🟢' : catScore.percentage >= 50 ? '🟡' : '🔴';
    md += `| **${catScore.title}** | ${statusIcon} | ${catScore.passedCount}/${catScore.totalCount} | **${catScore.percentage}%** |\n`;
  }
  md += `\n---\n\n`;

  md += `## 🚨 Failed Audits & Required Remediation\n\n`;

  if (diagnostics.length === 0) {
    md += `🎉 **Congratulations! Your project passes all 39 production readiness criteria with zero issues.**\n\n`;
  } else {
    for (const d of diagnostics) {
      const icon = d.severity === 'error' ? '❌ [ERROR]' : '⚠️ [WARN]';
      const catTitle = CATEGORIES[d.categoryId]?.title || d.categoryId;

      md += `### Check #${d.ruleNumber}: ${d.title} (${icon})\n`;
      md += `- **Category:** ${catTitle}\n`;
      md += `- **Issue:** ${d.message}\n`;
      if (d.filePath) {
        md += `- **File:** \`${d.filePath}\` ${d.line ? `(line ${d.line})` : ''}\n`;
      }
      md += `- **Help:** ${d.help}\n\n`;

      if (d.fixBlueprint) {
        md += `#### 🛠️ AI Fix Blueprint: ${d.fixBlueprint.title}\n`;
        md += `${d.fixBlueprint.summary}\n\n`;
        md += `**Execution Steps:**\n`;
        for (const step of d.fixBlueprint.steps) {
          md += `1. ${step}\n`;
        }
        if (d.fixBlueprint.codeTemplate) {
          md += `\n\`\`\`tsx\n${d.fixBlueprint.codeTemplate}\n\`\`\`\n`;
        }
      }
      md += `\n---\n\n`;
    }
  }

  md += `## ✅ Passed Audit Checklist (${passedRules.length}/39)\n\n`;
  for (const r of passedRules) {
    md += `- ✅ **Check #${r.number}: ${r.title}** — *${r.description}*\n`;
  }

  md += `\n---\n\n*Generated by [Audit Doctor](https://github.com/dqev/audit-doctor)*\n`;

  return md;
}
